spring:
  application:
    name: dubbo-provider
server:
  port: 81

  # Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
dubbo:
  application:
    name: ${spring.application.name}
# Dubbo Registry
  registry:
    address: zookeeper://127.0.0.1:2181
# Dubbo Protocol
  #dubbo.protocol.name=dubbo
  #dubbo.protocol.port=20880

  #dubbo.protocol.name=rest
  #dubbo.protocol.port=8083
    # protocols:
      #  p1:
      #   id: dubbo1
      #  name: dubbo
      #  port: 20881
      # host: 0.0.0.0

      #  p2:
      #    id: rest
      #    name: rest
      #    port: 8083
  #    host: 0.0.0.0

#dubbo.protocols.p3.id=dubbo3
#dubbo.protocols.p3.name=dubbo
#dubbo.protocols.p3.port=20883
#dubbo.protocols.p3.host=0.0.0.0


