@startuml
'https://plantuml.com/class-diagram

class Customer {

}

interface BMW

class BMW320
BMW320 --|> BMW

class BMW523
BMW523 --|> BMW

class Factory {
  + createBMW(int type): BMW
}

Factory ..> BMW320
Factory ..> BMW523

Customer ..> Factory

@enduml