#垂直分表策略
# 配置真实数据源
spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
# 配置第 1 个数据源
    datasource:
      names: m1
    m1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: 12345678
    # 指定表的分布情况 配置表在哪个数据库里，表名是什么。水平分表，分两个表：m1.course_1,m1.course_2
    sharding:
      tables:
        course:
          actual-data-nodes: m1.course_$->{1..2}
          # 指定表的主键生成策略
          key-generator:
            column: cid
            type: SNOWFLAKE
          #雪花算法的一个可选参数
            props:
              mykey-offset: 88
      #指定分片策略 约定cid值为偶数添加到course_1表。如果是奇数添加到course_2表。
      # 选定计算的字段
          table-strategy:
            inline:
              sharding-column: cid
              algorithm-expression: course_$->{cid%2+1}
    props:
      sql:
        show: true
