server:
  port: 8090

spring:
  application:
    name: integration
  # security:
  #  user:
    #  name: admin
    #  password: 123456
    #  roles: admin
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0