server:
  port: 8080

info:
  component: Security Authentication and Authorization
spring:
  application:
    name: SpringSecurityBoot
  security:
    auth:
      login-url: /api/auth/login
      fast-login-url: /api/auth/fastLogin
      refresh-token-url: /api/auth/refreshToken
      retrieve-user-profile-url: /api/auth/retrieveUserProfile
      reset-pwd-url: /api/auth/pwd/reset
      change-pwd-url: /api/auth/pwd/modify
      api-root-url: /api/**
    jwt:
      token-expiration-time: 1440
      refresh-token-exp-time: 43200
      token-signing-key: aGJnai1jbXMtdG9rZW4tc2VjcmV0LWtleQ==
      refresh-token-signing-key: aGJnai1kbXMtcmVmcmVzaC10b2tlbi1zZWNyZXQta2V5
      token-issuer: huangxiangquan
