# 无测试
version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: 'elasticsearch:7.6.2'
    restart: always
    privileged: true
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
      - bootstrap.memory_lock=true
    volumes:
      - ./es/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./es/data:/usr/share/elasticsearch/data #数据文件挂载
      - ./es/logs:/user/share/elasticsearch/logs
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1024M
        reservations:
          memory: 200M
  kibana:
    image: kibana:7.6.2
    container_name: kibana
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200 #设置访问elasticsearch的地址
      I18N_LOCALE: zh-CN
    ports:
      - '5601:5601'

  oap:
    container_name: oap
    image: 'apache/skywalking-oap-server:8.3.0-es7'
    ports:
      - '12800:12800'
      - '11800:11800'
    environment:
      - TZ=Asia/Shanghai
      - SW_STORAGE=elasticsearch7
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
    links:
      - elasticsearch:elasticsearch

  skywalking-ui:
    container_name: mysql
    image: 'apache/skywalking-ui:8.3.0'
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SW_OAP_ADDRESS=oap:12800
    ports:
      - '8088:8080'
    links:
      - oap=oap
