server:
  port: 8810

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/quartz_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    scheduler-name: "scheduler_test"
    job-store-type: jdbc

