#mongodb
# 单机模式 mongodb://name:pass@ip:port/database
# 集群模式 mongodb://user:pwd@ip1:port1,ip2:port2/database
spring:
  data:
    mongodb:
      uri: mongodb://testUser:123456@127.0.0.1:27017/test
      # host: 127.0.0.1
      # port: 27017
      # username: testUser
      # password: 123456
      # database: test
