#mongodb
# 单机模式 mongodb://name:pass@ip:port/database
# 集群模式 mongodb://user:pwd@ip1:port1,ip2:port2/database
mongo-plus:
  data:
    mongodb:
      host: 124.221.90.139
      port: 27017
      database: test
